#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          authing:
#            client-id: 6010d2ac2ef88cc6fa3f9f6d
#            client-secret: 8ee0a8fa78045b609dc37d37134df943
#            redirect-uri: 'http://localhost:8766/login/oauth2/code/authing'
#            client-authentication-method: post
#            scope:
#              - openid
#              - profile
#        provider:
#          authing:
#            issuer-uri: https://dmz3594.authing.cn/oidc
#            user-name-attribute: username
logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
spring:
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/messaging-client-oidc"
            scope: openid
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/messaging-client-authorization-code"
            scope: openid,email
            client-name: messaging-client-authorization-code
          messaging-client-client-credentials:
            provider: spring
            client-id: messaging-client
            client-secret: secret
            authorization-grant-type: client_credentials
            scope: openid,ceaas
            client-name: messaging-client-client-credentials
        provider:
          spring:
            issuer-uri: http://authserver:9000
messages:
  base-uri: http://authserver:9000/