spring:
  cloud:
    gateway:
      routes:
        - id: wings-authentication-route
          uri: lb://wings-authentication-dev
          predicates:
            - Path=/wings-authentication-dev/**
        - id: wings-config-server-route
          uri: lb://wings-config-server
          predicates:
            - Path=/wings-config-server/**