server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    metadata-map:
      zone: beijing
    lease-renewal-interval-in-seconds: 10
  client:
    registerWithEureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    prefer-same-zone-eureka: true
    region: beijing
spring:
  application:
    name: wings-service-discover
  cloud:
    loadbalancer:
      zone: beijing
      ribbon:
        enabled: true
      eureka:
        approximate-zone-from-hostname: false